# Site Settings
title: "Right to Reality"
description: "A brief description of your site."
url: "https://yourusername.github.io"
baseurl: "/docs" 

# Author
author:
  name: "Vagner Santana"
  email: "vsantana@nic.br"
  
# Theme
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Markdown & Syntax Highlighting
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink: pretty

# Exclude from build
exclude:
  - node_modules
  - vendor
  - README.md
  - LICENSE

# Collections (optional)
# collections:
#   docs:
#     output: true
#     permalink: /:collection/:name

# Default Front Matter (optional)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
